backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

use common\models\Note;
use common\models\Category;
use common\models\User;
use common\models\Login;
use common\models\SignUpForm;

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => ['class' => AccessControl::className(),
			'rules' => [
				[
					'actions' => [
						'signup',
						'login',
						'error'
					],
					'allow' => true,
				],
				[
					'actions' => [
						'logout',
						'index',
						'add-category',
						'update-category',
						'delete-category',
						'category',
						'down',
						'create',
						'update',
						'delete',
					],
					'allow' => true,
					'roles' => ['@'],
				],
			],
		],
	];
}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Category::find()->orderBy(['date' => SORT_ASC]);
		return $this->render('index', [
			'model' => $model
		]);
	}

	public function actionCategory($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$category = Category::find()->where(['id' => $id])->one();
		$model = Note::find()->where(['category_id' => $id]);
		return $this->render('category', [
			'category' => $category,
			'model' => $model,
		]);
	}

	public function actionCreate($id) {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Note();

		if (Yii::$app->request->isPost) {
			$model->title = Yii::$app->request->post()['Note']['title'];
			$model->desc = Yii::$app->request->post()['Note']['desc'];
			$model->category_id = $id;
			$model->date = date('Y-m-d');
			$model->save();
			return $this->redirect(['/site/category', 'id' => $id]);
		}

		return $this->render('create', [
			'model' => $model,
			'categorys' => $this->getCategorys(),
		]);
	}

	public function actionUpdate($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Note::findIdentity($id);

		if (Yii::$app->request->isPost) {
			$model->title = Yii::$app->request->post()['Note']['title'];
			$model->desc = Yii::$app->request->post()['Note']['desc'];
			$model->save();
			return $this->redirect(['/site/category', 'id' => $model->category_id]);
		}

		return $this->render('update', [
			'model' => $model,
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Note::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionAddCategory() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Category();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Category']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-category', [
			'model' => $model,
		]);
	}

	public function actionUpdateCategory($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Category::findOne($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Category']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-category', [
			'model' => $model,
		]);
	}

	public function actionDeleteCategory($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Category::findOne($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				if($user->isAdmin($user['id'])) {
					Yii::$app->user->login($user);
					return $this->goHome();
				}
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function getCategorys() {
		$categorys = [];
		$all_categorys = Category::find()->all();

		for ($i=0; $i < count($all_categorys); $i++) $categorys[$all_categorys[$i]->id] = $all_categorys[$i]->title;

		return $categorys;
	}

}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use yii\widgets\AlertLte;

?>
<div id="content">
	<div class="outer">
		<div class="inner bg-light lter">
			<div class="col-lg-12">

				<?php if (isset($this->blocks['content-header'])) { ?>
				<h1><?= $this->blocks['content-header'] ?></h1>
				<?php } else { ?>
				<h1>
					<?php
					if ($this->title !== null) {
						echo \yii\helpers\Html::encode($this->title);
					} else {
						echo \yii\helpers\Inflector::camel2words(
							\yii\helpers\Inflector::id2camel($this->context->module->id)
						);
						echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
					} ?>
				</h1>
				<?php } ?>

				<?=
				Breadcrumbs::widget([
					'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
					]) ?>
					<?= $content ?>
				</div>
			</div>
		</div>
	</div>

backend/views/layouts/header.php
<?php 
use common\models\User;
?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">Управление заметками</a>
            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> <?= User::findOne(Yii::$app->user->id)->username ?> <i class="caret"></i>

                        </a>
                        <ul class="dropdown-menu">
                            <li class="divider"></li>
                            <li>
                                <a tabindex="-1" href="/admin/site/logout">Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

backend/views/layouts/leftside.php
<?php

use adminlte\widgets\Menu;
use yii\helpers\Html;
use yii\helpers\Url;

use common\models\Category;

$category = [];
$all_category = Category::find()->all();

for ($i=0; $i < count($all_category); $i++) {
	$item = $all_category[$i];
	$category[] = [
		'label' => $item->title,
		'count' => $item->getCountNotes(),
		'url' => "/admin/site/category?id=$item->id",
		'active' => ($this->context->route == 'site/category' and $_GET['id'] == $item->id)
	];
}

?>

<div class="span3" id="sidebar">
	<ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
		<li class="<?= ($this->context->route == 'site/index') ? 'active' : '' ?>">
			<a href="/">Главная</a>
		</li>
		<?php foreach($category as $item): ?>
			<li class=" <?= (($item['active'] == 1) ? 'active' : '') ?>"><a href="<?= $item['url'] ?>"><span class="badge badge-info pull-right"><?= $item['count'] ?></span> <?= $item['label'] ?></a></li>
		<?php endforeach ?>
		<li class="<?= ($this->context->route == 'site/add-category') ? 'active' : '' ?>" ><a href="/admin/site/add-category"><i class="icon-plus"></i> Добавить категорию</a></li>
	</ul>
</div>

backend/views/layouts/login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use backend\assets\AdminLteAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <!-- Bootstrap -->
    <link href="/admin/public/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/admin/public/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="/admin/public/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
    <link href="/admin/public/assets/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="/admin/public/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <?php $this->head() ?>
</head>
<body class="login-page" id="login">

    <?php $this->beginBody() ?>

    <?= $content ?>

    <script src="/admin/public/vendors/jquery-1.9.1.min.js"></script>
    <script src="/admin/public/bootstrap/js/bootstrap.min.js"></script>
    <script src="/admin/public/vendors/easypiechart/jquery.easy-pie-chart.js"></script>
    <script src="/admin/public/assets/scripts.js"></script>
    <script>
        $(function() {
            // Easy pie charts
            $('.chart').easyPieChart({animate: 1000});
        });
    </script>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use backend\assets\AppAsset;
use backend\assets\AdminLteAsset;

//AppAsset::register($this);
$asset      = AdminLteAsset::register($this);
$baseUrl    = $asset->baseUrl;
use backend\assets\FontAwesomeAsset;
FontAwesomeAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <!-- Bootstrap -->
    <link href="/admin/public/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/admin/public/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="/admin/public/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
    <link href="/admin/public/assets/styles.css" rel="stylesheet" media="screen">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="/admin/public/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>

    <?= $this->render('header.php', ['baserUrl' => $baseUrl, 'title'=>Yii::$app->name]) ?>
  
<div class="container-fluid">
    <div class="row-fluid">
        <?= $this->render('leftside.php', ['baserUrl' => $baseUrl]) ?>
        <?= $this->render('content.php', ['content' => $content]) ?>
        <?= $this->render('footer.php', ['baserUrl' => $baseUrl]) ?>
        <?= $this->render('rightside.php', ['baserUrl' => $baseUrl]) ?>
    </div>
    <hr>
    <footer>
        <p>&copy; 2017 Заметки</p>
    </footer>
</div>

  <?php $this->endBody() ?>
  <script src="/admin/public/vendors/jquery-1.9.1.min.js"></script>
  <script src="/admin/public/bootstrap/js/bootstrap.min.js"></script>
  <script src="/admin/public/vendors/easypiechart/jquery.easy-pie-chart.js"></script>
  <script src="/admin/public/assets/scripts.js"></script>
  <script>
    $(function() {$('.chart').easyPieChart({animate: 1000});});
  </script>
</body>
</html>
<?php $this->endPage() ?>