backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

use common\models\Note;
use common\models\Category;
use common\models\User;
use common\models\Login;
use common\models\SignUpForm;

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => ['class' => AccessControl::className(),
			'rules' => [
				[
					'actions' => [
						'signup',
						'login',
						'error'
					],
					'allow' => true,
				],
				[
					'actions' => [
						'logout',
						'index',
						'add-category',
						'update-category',
						'delete-category',
						'category',
						'down',
						'create',
						'update',
						'delete',
					],
					'allow' => true,
					'roles' => ['@'],
				],
			],
		],
	];
}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Category::find()->orderBy(['date' => SORT_ASC]);
		return $this->render('index', [
			'model' => $model
		]);
	}

	public function actionCategory($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$category = Category::find()->where(['id' => $id])->one();
		$model = Note::find()->where(['category_id' => $id]);
		return $this->render('category', [
			'category' => $category,
			'model' => $model,
		]);
	}

	public function actionCreate($id) {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Note();

		if (Yii::$app->request->isPost) {
			$model->title = Yii::$app->request->post()['Note']['title'];
			$model->desc = Yii::$app->request->post()['Note']['desc'];
			$model->category_id = $id;
			$model->date = date('Y-m-d');
			$model->save();
			return $this->redirect(['/site/category', 'id' => $id]);
		}

		return $this->render('create', [
			'model' => $model,
			'categorys' => $this->getCategorys(),
		]);
	}

	public function actionUpdate($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Note::findIdentity($id);

		if (Yii::$app->request->isPost) {
			$model->title = Yii::$app->request->post()['Note']['title'];
			$model->desc = Yii::$app->request->post()['Note']['desc'];
			$model->save();
			return $this->redirect(['/site/category', 'id' => $model->category_id]);
		}

		return $this->render('update', [
			'model' => $model,
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Note::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionAddCategory() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Category();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Category']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-category', [
			'model' => $model,
		]);
	}

	public function actionUpdateCategory($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Category::findOne($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Category']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-category', [
			'model' => $model,
		]);
	}

	public function actionDeleteCategory($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Category::findOne($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				if($user->isAdmin($user['id'])) {
					Yii::$app->user->login($user);
					return $this->goHome();
				}
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function getCategorys() {
		$categorys = [];
		$all_categorys = Category::find()->all();

		for ($i=0; $i < count($all_categorys); $i++) $categorys[$all_categorys[$i]->id] = $all_categorys[$i]->title;

		return $categorys;
	}

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller {

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
		];
	}

	public function actionIndex() {
		return $this->redirect(['admin/']);
	}


}

backend/views/site/add-category.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Новый категория');

?>
<div class="span9" id="content">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'title')->textInput() ?>

				<div class="form-group center">
					<?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/category.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Заметки');
$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
		'pageSize' => 20,
	],
]);

?>
<div class="span9" id="content">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="contact-index">
				<?= Html::a(Yii::t('app','Добавить заметку'), ['/site/create', 'id' => $_GET['id']]) ?>
				<div class="fa-br"></div>
				<br>
				<?php
				echo GridView::widget([
					'dataProvider' => $dataProvider,
					'layout' => "{items}\n{pager}",
					'columns' => [
						'title',
						'desc',
						[
							'class' => 'yii\grid\ActionColumn',
							'header'=>'Действия', 
							'headerOptions' => ['width' => '80'],
							'template' => '{update} {delete}',
							'buttons' => [
								'update' => function ($url, $model) {
									return Html::a('<span class="icon icon-pencil"></span>', ['site/update', 'id'=>$model->id ], [
										'title' => Yii::t('app', 'lead-update'),
									]);
								},
								'delete' => function ($url, $model) {
									return Html::a('<span class="icon icon-trash"></span>', ['site/delete', 'id'=>$model->id ], [
										'title' => Yii::t('app', 'lead-delete'),
									]);
								}
							],
						],
					],
				]);
				?>

			</div>

		</div>
	</div>
</div>

backend/views/site/create.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;

$this->title = Yii::t('app', 'Новая заметка');

?>
<div class="span9" id="content">
	<div class="panel panel-default">
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
				<?= $form->field($model, 'desc')->textArea() ?>

				<div class="form-group center">
					<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' =>  'btn btn-success']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Все категории');

$dataProvider = new ActiveDataProvider([
  'query' => $model,
  'pagination' => [
   'pageSize' => 20,
 ],
]);

?>

<div class="span9" id="content">
<?php
echo GridView::widget([
  'dataProvider' => $dataProvider,
  'layout' => "{items}\n{pager}",
  'columns' => [
    'title',
    [
      'class' => 'yii\grid\ActionColumn',
      'header'=>'Действия', 
      'headerOptions' => ['width' => '80'],
      'template' => '{update} {delete}',
      'buttons' => [
        'update' => function ($url, $model) {
          return Html::a('<span class="icon icon-pencil"></span>', ['site/update-org', 'id'=>$model->id ], [
            'title' => Yii::t('app', 'lead-update'),
          ]);
        },
        'delete' => function ($url, $model) {
          return Html::a('<span class="icon icon-trash"></span>', ['site/delete-org', 'id'=>$model->id ], [
            'title' => Yii::t('app', 'lead-delete'),
          ]);
        }
      ],
    ],
  ],
]);
?>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">
	<?php $form = ActiveForm::begin(
		[
			'action' => '',
			'options' => [
				'class' => 'form-signin'
			]
		]
		); ?>

		<h2 class="form-signin-heading">Вход</h2>

		<?= $form->field($model, 'email')->textInput(['autofocus' => true])->input('text', ['placeholder'=>'email']) ?>
		<?= $form->field($model, 'password')->passwordInput()->input('password', ['placeholder'=>'Password'])?>

		<?= Html::submitButton('Войти', ['class' => 'btn btn-large btn-primary']) ?>
		<?= Html::a('Регистрация', ['/site/signup'],['class' => 'btn']) ?>
		<?php ActiveForm::end(); ?>

</div> <!-- /container -->

backend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">
	<?php $form = ActiveForm::begin(
		[
			'action' => '',
			'options' => [
				'class' => 'form-signin'
			]
		]
		); ?>

		<h2 class="form-signin-heading">Вход</h2>

		<?= $form->field($model, 'username')->textInput(['autofocus' => true])->input('text', ['placeholder'=>'Логин']) ?>
		<?= $form->field($model, 'email')->textInput()->input('text', ['placeholder'=>'email']) ?>
		<?= $form->field($model, 'password')->passwordInput()->input('password', ['placeholder'=>'Пароль'])?>

		<?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		<?= Html::a('Войти', ['/site/login'],['class' => 'btn']) ?>

		<?php ActiveForm::end(); ?>

</div> <!-- /container -->

backend/views/site/update.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;

$this->title = 'Обновить';

?>

<div class="span9" id="content">
	<div class="panel panel-default">
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
				<?= $form->field($model, 'desc')->textArea() ?>

				<div class="form-group center">
					<?= Html::submitButton(Yii::t('app', 'Обновить'), ['class' =>  'btn btn-success']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>